name: Build and Test on Windows

on: push

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_CONFIGURATION}}

    - name: Run executable
      run: |
        echo "Find and execute"
        $exePath = Get-ChildItem -Path "build" -Filter "*.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
        if ($exePath) {
          echo "Executable found: $exePath"
          & $exePath
        } else {
          echo "No Executable found."
        }
      shell: pwsh
