name: Build and Test on Windows

on: push

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_CONFIGURATION}}

    - name: Run executable
      run: |
        $exePath = "${{github.workspace}}/build/Release/brightener.exe"
        if (Test-Path $exePath) {
          Write-Host "Executable found: $exePath"
          & $exePath
        } else {
          Write-Host "No Executable found at $exePath"
        }
      shell: pwsh
